//모든 페이지를 감싼다
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./global.css";
import DashboardWrapper from "./DashboardWrapper";
import { ThemeProvider } from "next-themes";

const NotoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${NotoSansKR.className} font-medium antialiased`}>
        <ThemeProvider attribute="class">
          <DashboardWrapper>{children}</DashboardWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
